version: '3.1'
services:
  db:
    image: mysql
    restart: always
    container_name: mysql_ending_credits
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ending_credits
    ports:
      - "3306:3306"
    volumes:
      - .data/:/var/lib/mysql

